baseurl: "/Imvertor-SAAS"
# apiname: "BRK Bevragen"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Imvertor SAAS
    subnav:
      - title: Functie
        path: /
      - title: Handleiding
        path: /handleiding
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  
remote_theme: melsk-r/Imvertor-jekyll-theme

github: melsk-r/Imvertor-saas

theme: jekyll-theme-time-machine

project_name: /Imvertor
